### ISSUE TITLE
최신 파일이 다운로드가 안되고 넘어갑니다

### ISSUE THREAD

**Issue by kkookko12** [dc-koromo/koromo-copy-windows#35]
약 2주 정도 된 거 같은데 최신 파일들은 다운 속도가 나타나지 않고 빈 폴더인 상태로 다운이 완료되어 버리네요...

**Comment by dc-koromo** [comment]
제 환경에선 나타나지 않는 문제예요
어떤 작품이 다운로드되지 않는 건가요?

**Comment by yoyeoun** [comment]
저랑 똑같은 현상이시네요. 저도 2주정도 사용 못 하고 있는것 같음.
재개발 하신다는 얘기만 듣고 멍하니 기다리는중..
작품은 다운로드는 진행이 되는데 데이터를 내려받지 않아요.
특정작품이 그런게 아니라 모든 작품이 다 그러함. 예전에 받았던것도 다시 받으면
안 받아짐.
![1231111](https://user-images.githubusercontent.com/59349301/71565682-9fd2ca80-2af4-11ea-8e2a-94950359be06.jpg)

**Comment by dc-koromo** [comment]
구버전이네요...
https://github.com/dc-koromo/koromo-copy-windows/releases/tag/1.17
이거 써주세요
1.16, 1.17 버전은 자동업데이트를 지원하지 않아요
다음버전인 1.18부터 자동업데이트 다시 구현해둘께요

**Comment by kkookko12** [comment]
원래 폴더에 붙여넣으면 되는거죠? 감사합니다!
